import { enrichRecordScores } from "./scoring";
import type {
  PlatformDefinition,
  PlatformId,
  PlatformPresenceLevel,
  ProductBlend,
  ProductMonitorRecord,
  MonitorMeta,
} from "./types";

export const monitorMeta: MonitorMeta = {
  benchmarkDate: "2026-06-22",
  platformCount: 12,
  productTypeCount: 221,
  listingCount: 617,
  sourceFiles: [
    "对标平台多肽产品矩阵（2026-06-22）.xlsx",
    "对标平台供应商备货建议_20260622.md",
  ],
  budgetSplit: {
    core: "55%–65%（通用单体原料，6–8 周预测用量）",
    trial: "25%–30%（常规小批量，2–4 周预测用量）",
    avoid: "订单制（客户预测 → 资质确认 → 定金 → 排产）",
  },
};

export const platforms: PlatformDefinition[] = [
  { id: "elite_peps", name: "Elite Peps Australia" },
  { id: "ozpeps", name: "OzPeps" },
  { id: "aussie_peptides", name: "Aussie Peptides" },
  { id: "optic_labs", name: "Optic Labs" },
  { id: "rainbow_peptide", name: "Rainbow Peptide" },
  { id: "premiumpeps", name: "PremiumPeps" },
  { id: "bt7", name: "BT7" },
  { id: "biolongevity", name: "BioLongevity Labs" },
  { id: "limitless", name: "Limitless Biotech" },
  { id: "amino_usa", name: "Amino USA" },
  { id: "gl_vitality", name: "GL Vitality Drips" },
  { id: "biov8", name: "BIOV8" },
];

const EMPTY_PRESENCE = Object.fromEntries(
  platforms.map((p) => [p.id, 0 as PlatformPresenceLevel]),
) as Record<PlatformId, PlatformPresenceLevel>;

function p(
  presence: Partial<Record<PlatformId, PlatformPresenceLevel>>,
  listings: Partial<Record<PlatformId, string>>,
): {
  platformPresence: Record<PlatformId, PlatformPresenceLevel>;
  platformListings: Partial<Record<PlatformId, string>>;
  platformCoverage: number;
} {
  const platformPresence = { ...EMPTY_PRESENCE, ...presence };
  const platformCoverage = Object.values(platformPresence).filter((v) => v > 0)
    .length;
  return { platformPresence, platformListings: listings, platformCoverage };
}

const rawRecords: Omit<
  ProductMonitorRecord,
  "compositeScore" | "scores"
>[] = [
  {
    id: "pm-bpc157",
    product: "BPC-157",
    displayNameZh: "BPC-157",
    primarySpec: "10mg 冻干粉",
    category: "recovery",
    tier: "core",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 2,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 2,
        premiumpeps: 1,
        bt7: 1,
        biolongevity: 2,
        limitless: 3,
        amino_usa: 3,
        gl_vitality: 1,
        biov8: 2,
      },
      {
        elite_peps: "BPC-157 10mg (Stable Gastric Pentadecapeptide)",
        ozpeps: "BPC-157 20mg；BPC-157 10mg",
        aussie_peptides: "BPC-157 (10mg)",
        optic_labs: "BPC-157 5mg / 10mg",
        rainbow_peptide: "bpc 157 capsules 500mcg；bpc 157",
        premiumpeps: "BPC-157 (10mg)",
        bt7: "BPC‑157 10mg",
        biolongevity: "BPC-157 BioStrips；BPC-157 (10mg)",
        limitless:
          "BPC-157 Capsules；BPC-157；BPC-157 Acetate；BPC-157 Acetate Spray；BPC-157 Spray",
        amino_usa:
          "BPC-157/KPV Blend (60 Count)；BPC-157 20mg；BPC-157 500mcg (60 Count)；BPC-157 5mg；BPC-157 15mg；BPC-157 10mg；GHK-Cu + TB4 + BPC-157 Blend",
        gl_vitality: "BPC-157",
        biov8: "BPC-157；BPC-157 ICCC",
      },
    ),
    commonBlends: ["blend-bpc-tb", "blend-glow", "blend-klow"],
    specProfile: {
      primarySpecs: ["10mg", "5mg", "500mcg capsules"],
      consensusSpec: "10mg 冻干粉",
      forms: ["冻干粉", "胶囊", "喷雾", "BioStrips"],
      notes: "唯一 12/12 全平台覆盖；也是 BPC/TB、GLOW、KLOW 组合的基础原料",
    },
    supplyMetrics: {
      stockWeeks: "6–8 周",
      stockMode: "raw_material",
      leadTimeDays: 21,
      reorderNote: "补货点 = 交付周期内预测需求 + 安全库存",
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: [
      "TGA 监管敏感产品，RUO 标签不能构成合法进口/持有依据",
      "需设置文件门槛的受控库存，仅向可证明合法资质的 B2B 客户放货",
    ],
    stockingLogic:
      "唯一覆盖全部 12 个平台；优先作为母库存深备，支持单品与多种组合分装",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-mots-c",
    product: "MOTS-C",
    displayNameZh: "MOTS-C",
    primarySpec: "10mg / 40mg",
    category: "metabolic",
    tier: "core",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 2,
        ozpeps: 2,
        aussie_peptides: 3,
        optic_labs: 1,
        rainbow_peptide: 2,
        premiumpeps: 1,
        bt7: 3,
        biolongevity: 1,
        limitless: 1,
        amino_usa: 2,
        gl_vitality: 1,
        biov8: 2,
      },
      {
        elite_peps:
          "MOTS-c 10mg (Mitochondrial-Derived Peptide)；MOTS-c 40mg",
        ozpeps: "MOTS-c 10mg；MOTS-c 40mg",
        aussie_peptides: "MOTS-C (10mg)；MOTS-C (20mg)；MOTS-C (40mg)",
        optic_labs: "MOTS-C 10mg / 40mg",
        rainbow_peptide: "mots c capsules 10mg；mots c",
        premiumpeps: "Mots-c (10mg)",
        bt7: "Mots 10mg；Mots 20mg；Mots-c – 20mg；MOTS-C – 10mg",
        biolongevity: "MOTS-c (10mg)",
        limitless: "MOTS-C",
        amino_usa: "MOTS-C 40mg；MOTS-C 10mg",
        gl_vitality: "MOTS-C",
        biov8: "MOTS-C；MOTS-C ICCC",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "40mg", "20mg"],
      consensusSpec: "10mg、40mg",
      forms: ["冻干粉", "胶囊"],
      notes: "澳洲与美国平台均高度覆盖，兼具单品与线粒体/抗衰组合需求",
    },
    supplyMetrics: {
      stockWeeks: "6–8 周",
      stockMode: "raw_material",
      leadTimeDays: 21,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["研究用途产品，需客户资质审核"],
    stockingLogic: "12/12 全平台覆盖；规格相对集中，适合标准化备货",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-ghk-cu",
    product: "GHK-Cu",
    displayNameZh: "GHK-Cu 蓝铜肽",
    primarySpec: "50mg / 100mg",
    category: "cosmetic",
    tier: "core",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        aussie_peptides: 2,
        optic_labs: 1,
        rainbow_peptide: 2,
        premiumpeps: 3,
        bt7: 3,
        biolongevity: 2,
        limitless: 3,
        amino_usa: 2,
        gl_vitality: 1,
        biov8: 3,
      },
      {
        elite_peps: "GHK-Cu 100mg (Copper Peptide)",
        aussie_peptides: "GHK-Cu (50mg)；GHK-Cu (100mg)",
        optic_labs: "GHK-CU 50mg / 100mg",
        rainbow_peptide: "ghk cu capsules 50mg；ghk cu",
        premiumpeps:
          "GHK-Cu Peptide Hair Growth Serum；GHK-Cu Scalp Micro-Infusion System；GHK-Cu Peptide Facial Serum；GHK-Cu (50mg)",
        bt7:
          "GHK-CU Peptide Face Cream Bundle；GHK-CU Copper Peptide Face Cream；GHK-Cu – 100mg",
        biolongevity: "GHK-Cu BioStrips；GHK-Cu Copper Peptide (50mg)",
        limitless: "GHK-Cu Capsules；GHK-Cu (Copper Peptide)；GHK-Cu Spray",
        amino_usa: "GHK-Cu 100mg；GHK-Cu 50mg",
        gl_vitality: "GHK-Cu",
        biov8:
          "Copper Peptide GHK-CU Face Serum 30 ml；Copper Peptide Moisturising Day Cream 50g；Copper Peptide Hydrating Night Cream 50g；GHK-Cu Injectable ICCC",
      },
    ),
    commonBlends: ["blend-glow", "blend-klow"],
    specProfile: {
      primarySpecs: ["50mg", "100mg"],
      consensusSpec: "50mg、100mg",
      forms: ["冻干粉", "精华", "面霜", "胶囊", "喷雾"],
      notes: "剂型和客户类型最丰富，可延展为冻干粉、精华、面霜及 GLOW/KLOW",
    },
    supplyMetrics: {
      stockWeeks: "6–8 周",
      stockMode: "raw_material",
      leadTimeDays: 21,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: [
      "TGA 监管敏感产品",
      "Injectable ICCC 等形态需额外合规审核",
    ],
    stockingLogic: "11/12 平台覆盖；优先母库存，支持多形态下游交付",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-tb500",
    product: "TB-500",
    displayNameZh: "TB-500",
    primarySpec: "10mg",
    category: "recovery",
    tier: "core",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 1,
        premiumpeps: 1,
        bt7: 1,
        biolongevity: 1,
        limitless: 3,
        amino_usa: 3,
      },
      {
        elite_peps: "TB-500 10mg (Thymosin Beta-4 Analog)",
        ozpeps: "TB-500 10mg",
        aussie_peptides: "TB-500 (10mg)",
        optic_labs: "TB-500 5mg / 10mg",
        rainbow_peptide: "tb 500",
        premiumpeps: "TB-500 (10mg)",
        bt7: "TB-500 – 10mg",
        biolongevity: "TB-500 (10mg)",
        limitless:
          "TB-500 (Thymosin Beta-4)；TB-500 Thymosin Beta-4 Fragment 1-4；TB-500 Thymosin Beta-4 Fragment 17-23",
        amino_usa: "TB-500 Fragment (17-23) 10mg；TB-500 5mg；TB-500 10mg",
      },
    ),
    commonBlends: ["blend-bpc-tb", "blend-glow", "blend-klow"],
    specProfile: {
      primarySpecs: ["10mg", "5mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "Fragment 变体"],
    },
    supplyMetrics: {
      stockWeeks: "6–8 周",
      stockMode: "raw_material",
      leadTimeDays: 21,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["Thymosin Beta-4 类监管敏感；受控库存放货"],
    stockingLogic: "10/12 平台覆盖；修复类组合核心原料",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-cjc-ipa",
    product: "CJC-1295 + Ipamorelin",
    displayNameZh: "CJC-1295 + Ipamorelin",
    primarySpec: "5mg+5mg（总量 10mg）",
    category: "metabolic",
    tier: "core",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 1,
        bt7: 1,
        biolongevity: 1,
        limitless: 1,
        amino_usa: 1,
        gl_vitality: 1,
        biov8: 2,
      },
      {
        elite_peps: "CJC-1295 No DAC + Ipamorelin 10mg (5mg/5mg Blend)",
        ozpeps: "CJC-1295 + Ipamorelin 10mg",
        aussie_peptides: "CJC-1295 (no DAC) + Ipamorelin (10mg)",
        optic_labs: "CJC-1295 no DAC + Ipamorelin 10mg",
        rainbow_peptide: "cjc 1295 ipamorelin blend 10mg 5mg",
        bt7: "CJC-1295 + Ipamorelin Blend",
        biolongevity: "CJC 1295 & Ipamorelin Blend (10mg) (No DAC)",
        limitless: "CJC-1295 + Ipamorelin Blend",
        amino_usa: "CJC1295 no DAC + Ipamorelin 5/5mg",
        gl_vitality: "CJC-1295 / Ipamorelin",
        biov8: "CJC 1295/ Ipamorelin；CJC 1295/ Ipamorelin ICCC",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["5mg+5mg", "10mg blend"],
      consensusSpec: "5mg+5mg，总量 10mg",
      forms: ["预混冻干粉"],
      notes: "各平台规格高度统一，适合标准化白牌交付",
    },
    supplyMetrics: {
      stockWeeks: "6–8 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 28,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["GH 分泌相关肽类，处方/研究用途需资质审核"],
    stockingLogic: "11/12 平台覆盖；规格统一，适合标准化成品备货",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-tesamorelin",
    product: "Tesamorelin",
    displayNameZh: "Tesamorelin",
    primarySpec: "10mg",
    category: "metabolic",
    tier: "core",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 2,
        ozpeps: 1,
        aussie_peptides: 3,
        optic_labs: 1,
        rainbow_peptide: 1,
        premiumpeps: 1,
        bt7: 1,
        biolongevity: 1,
        amino_usa: 3,
        gl_vitality: 1,
        biov8: 2,
      },
      {
        elite_peps: "Tesamorelin 10mg Australia；Tesamorelin",
        ozpeps: "Tesamorelin 10mg",
        aussie_peptides: "Tesamorelin (10mg)；Tesamorelin (20mg)；Tesamorelin (5mg)",
        optic_labs: "Tesamorelin 10mg",
        rainbow_peptide: "tesamorelin",
        premiumpeps: "Tesamorelin (10mg)",
        bt7: "Tesamorelin – 20mg",
        biolongevity: "Tesamorelin (10mg)",
        amino_usa: "Tesamorelin 5mg；Tesamorelin 2mg；Tesamorelin 10mg",
        gl_vitality: "Tesamorelin",
        biov8: "Tesamorelin；Tesamorelin ICCC",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "5mg", "20mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉"],
    },
    supplyMetrics: {
      stockWeeks: "6–8 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 28,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["跨研究用途和处方平台覆盖"],
    stockingLogic: "11/12 平台覆盖；单品规格相对标准化",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-bpc-tb-blend",
    product: "BPC-157 + TB-500",
    displayNameZh: "BPC-157 + TB-500 组合",
    primarySpec: "10mg+10mg",
    category: "blend",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 1,
        bt7: 1,
        biolongevity: 2,
        limitless: 1,
        amino_usa: 2,
        biov8: 2,
      },
      {
        elite_peps: "BPC-157 + TB-500 20mg (10mg/10mg Blend)",
        ozpeps: "BPC-157 / TB-500 Blend 10mg",
        aussie_peptides: "BPC-157 + TB-500 (10mg)",
        optic_labs: "BPC-157 + TB-500 10mg / 20mg",
        rainbow_peptide: "bpc 157 tb 500 blend",
        bt7: "BPC-157 + TB-500 Research Blend – 10 mg / 10 mg",
        biolongevity:
          "Regeno Blend (BPC-157, TB-500, Cartalax) 30mg；BPC-157 TB-500 Blend (10mg)",
        limitless: "BPC-157 Acetate + TB-500 Fragment 17-23 Blend Spray",
        amino_usa: "BPC157 + TB500 Blend 20mg；BPC157 + TB500 Blend 10mg",
        biov8: "BPC-157/Thymosin Beta-4 - Vial；BPC157/ Thymosin Beta 4 ICCC",
      },
    ),
    commonBlends: ["blend-bpc-tb"],
    specProfile: {
      primarySpecs: ["10mg+10mg", "10mg blend"],
      consensusSpec: "10mg+10mg",
      forms: ["预混冻干粉", "喷雾"],
    },
    supplyMetrics: {
      stockWeeks: "2–4 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 14,
      reorderNote: "可由 BPC-157、TB-500 母库存快速分装",
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["组合产品监管敏感度叠加"],
    stockingLogic: "10/12 平台覆盖；最普遍的修复类组合，小批量成品",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-glow",
    product: "GLOW",
    displayNameZh: "GLOW 组合",
    primarySpec: "GHK-Cu 50mg + BPC-157 10mg + TB-500 10mg（70mg）",
    category: "blend",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 2,
        optic_labs: 1,
        premiumpeps: 1,
        bt7: 2,
        biolongevity: 1,
        limitless: 2,
      },
      {
        elite_peps: "GLOW 70 Rejuvenation Blend (70mg Total)",
        ozpeps: "GLOW 70mg",
        aussie_peptides: "GLOW Peptide Blend (50mg)；GLOW Peptide Blend (70mg)",
        optic_labs: "GLOW70 (BPC-157 10mg + GHK-CU 50mg + TB-500 10mg)",
        premiumpeps: "GLOW (70mg)",
        bt7: "Glow 70mg；GLOW blend – 70 mg (GHK-Cu 50 mg / TB-500 10 mg / BPC-157 10 mg)",
        biolongevity: "GLOW Blend (GHK-Cu, BPC-157, TB-500) 70mg",
        limitless: "Glow Blend；Glow Blend Spray",
      },
    ),
    commonBlends: ["blend-glow"],
    specProfile: {
      primarySpecs: ["70mg total", "50mg blend"],
      consensusSpec: "70mg（GHK-Cu 50 + BPC-157 10 + TB-500 10）",
      forms: ["预混冻干粉", "喷雾"],
    },
    supplyMetrics: {
      stockWeeks: "延迟分装",
      stockMode: "delayed_fill",
      leadTimeDays: 7,
      reorderNote: "收到订单后由核心单体库存组合分装",
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["三肽组合，需组合检测与标签审核"],
    stockingLogic: "8/12 平台覆盖；延迟分装，不压成品库存",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-klow",
    product: "KLOW",
    displayNameZh: "KLOW 组合",
    primarySpec: "GLOW + KPV 10mg（80mg total）",
    category: "blend",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 1,
        premiumpeps: 1,
        biolongevity: 1,
      },
      {
        elite_peps: "KLOW Master Blend (80mg Total)",
        ozpeps: "KLOW 80mg",
        aussie_peptides: "KLOW Peptide Blend (80mg)",
        optic_labs:
          "KLOW80 (BPC-157 10mg + GHK-CU 50mg + TB-500 10mg + KPV 10mg)",
        rainbow_peptide: "klow blend",
        premiumpeps: "KLOW (80mg)",
        biolongevity: "KLOW Blend (GHK-Cu, BPC-157, TB-500, KPV) 80mg",
      },
    ),
    commonBlends: ["blend-klow"],
    specProfile: {
      primarySpecs: ["80mg total"],
      consensusSpec: "80mg（GLOW 配方 + KPV 10mg）",
      forms: ["预混冻干粉"],
    },
    supplyMetrics: {
      stockWeeks: "延迟分装",
      stockMode: "delayed_fill",
      leadTimeDays: 7,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["客单价较高但需求不宜高估"],
    stockingLogic: "7/12 平台覆盖；延迟分装，按订单组合",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-pt141",
    product: "PT-141",
    primarySpec: "10mg",
    category: "other",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 1,
        bt7: 2,
        biolongevity: 2,
        amino_usa: 1,
        gl_vitality: 1,
        biov8: 1,
      },
      {
        elite_peps: "PT-141 10mg (Bremelanotide)",
        ozpeps: "PT-141 10mg",
        aussie_peptides: "PT-141 (10mg)",
        optic_labs: "PT-141 10mg",
        rainbow_peptide: "pt 141",
        bt7: "PT-141-10mg-Research；PT-141 Research Material – 10 mg",
        biolongevity: "PT-141+ BioStrips；PT-141 (5mg)",
        amino_usa: "PT-141 10mg",
        gl_vitality: "PT-141",
        biov8: "Bremelanotide PT-141",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "5mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "BioStrips"],
    },
    supplyMetrics: {
      stockWeeks: "2–4 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 21,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["Bremelanotide 受管制关注"],
    stockingLogic: "10/12 平台覆盖；规格集中，小批量成品",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-dsip",
    product: "DSIP",
    primarySpec: "10mg",
    category: "neuro",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 2,
        bt7: 1,
        biolongevity: 1,
        limitless: 2,
        amino_usa: 1,
        biov8: 2,
      },
      {
        elite_peps: "DSIP 15mg (Delta Sleep-Inducing Peptide)",
        ozpeps: "DSIP 10mg",
        aussie_peptides: "DSIP (10mg)",
        optic_labs: "DSIP 10mg",
        rainbow_peptide: "dsip capsules 5mg；dsip",
        bt7: "DSIP – 5mg",
        biolongevity: "DSIP (Delta Sleep-Inducing Peptide) (5mg)",
        limitless: "DSIP Delta Sleep-Inducing Peptide；DSIP Spray",
        amino_usa: "DSIP 5mg",
        biov8: "DSIP (DELTA SLEEP INDUCING PEPTIDE) NASAL SPRAY；dsip iccc",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "5mg", "15mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "胶囊", "喷雾"],
    },
    supplyMetrics: {
      stockWeeks: "2–4 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 21,
    },
    auRegulatoryRisk: "low",
    regulatoryNotes: [],
    stockingLogic: "10/12 平台覆盖；神经肽产品线基础 SKU",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-kpv",
    product: "KPV",
    primarySpec: "10mg",
    category: "immune",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 2,
        bt7: 1,
        biolongevity: 1,
        limitless: 2,
        amino_usa: 2,
        biov8: 1,
      },
      {
        ozpeps: "KPV 10mg",
        aussie_peptides: "KPV (10mg)",
        optic_labs: "KPV 10mg",
        rainbow_peptide: "kpv capsules 4mg；kpv",
        bt7: "KPV – 10mg",
        biolongevity: "KPV (10mg)",
        limitless: "KPV Capsules；KPV",
        amino_usa: "KPV 10mg；KPV 5mg",
        biov8: "KPV Capsules - 60 capsules",
      },
    ),
    commonBlends: ["blend-klow"],
    specProfile: {
      primarySpecs: ["10mg", "5mg", "4mg capsules"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "胶囊"],
    },
    supplyMetrics: {
      stockWeeks: "2–4 周",
      stockMode: "raw_material",
      leadTimeDays: 21,
      reorderNote: "原料为主，用于 KLOW 和胃肠道组合",
    },
    auRegulatoryRisk: "low",
    regulatoryNotes: [],
    stockingLogic: "9/12 平台覆盖；原料为主，支持 KLOW 组合",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-epitalon",
    product: "Epitalon",
    primarySpec: "10mg",
    category: "metabolic",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 2,
        bt7: 3,
        biolongevity: 1,
        amino_usa: 2,
        gl_vitality: 1,
        biov8: 1,
      },
      {
        ozpeps: "Epitalon 10mg",
        aussie_peptides: "Epitalon (10mg)",
        optic_labs: "Epithalong 10mg",
        rainbow_peptide: "epithalon capsules 10mg；epithalon",
        bt7: "Epitalon 50mg；Epithalon – 50mg；Epithalon – 10 mg",
        biolongevity: "Epithalon (20mg)",
        amino_usa: "Epithalon (Epitalon) 50mg；Epithalon (Epitalon) 10mg",
        gl_vitality: "Epitalon",
        biov8: "Epitalon",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "50mg", "20mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "胶囊"],
    },
    supplyMetrics: {
      stockWeeks: "2–4 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 21,
    },
    auRegulatoryRisk: "low",
    regulatoryNotes: [],
    stockingLogic: "9/12 平台覆盖；抗衰产品线常见 SKU",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-semax",
    product: "Semax",
    primarySpec: "10mg",
    category: "neuro",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 2,
        bt7: 1,
        limitless: 2,
        amino_usa: 1,
        biov8: 2,
      },
      {
        elite_peps: "Semax 10mg Australia",
        ozpeps: "Semax 10mg",
        aussie_peptides: "Semax (10mg)",
        optic_labs: "Semax 10mg",
        rainbow_peptide: "semax capsules 10mg；semax",
        bt7: "Semax – (various)",
        limitless: "Semax；Semax Spray",
        amino_usa: "Semax 30mg",
        biov8: "Semax；Semax ICCC",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "30mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "胶囊", "喷雾"],
    },
    supplyMetrics: {
      stockWeeks: "2–4 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 21,
      reorderNote: "与 Selank 共线小批量",
    },
    auRegulatoryRisk: "low",
    regulatoryNotes: [],
    stockingLogic: "9/12 平台覆盖；神经肽系列",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-selank",
    product: "Selank",
    primarySpec: "10mg",
    category: "neuro",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 2,
        amino_usa: 2,
        biov8: 2,
      },
      {
        elite_peps: "Selank 10mg Australia",
        ozpeps: "Selank 10mg",
        aussie_peptides: "Selank (10mg)",
        optic_labs: "Selank 10mg",
        rainbow_peptide: "selank capsules 10mg；selank",
        amino_usa: "Selank 10mg；Selank 5mg",
        biov8: "Selank；Selank ICCC",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "5mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "胶囊"],
    },
    supplyMetrics: {
      stockWeeks: "2–4 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 21,
      reorderNote: "与 Semax 共线小批量",
    },
    auRegulatoryRisk: "low",
    regulatoryNotes: [],
    stockingLogic: "7/12 平台覆盖；神经肽系列",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-ta1",
    product: "Thymosin Alpha-1",
    displayNameZh: "胸腺肽 α1",
    primarySpec: "10mg",
    category: "immune",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        optic_labs: 1,
        rainbow_peptide: 2,
        bt7: 1,
        biolongevity: 2,
        limitless: 2,
        amino_usa: 1,
        gl_vitality: 1,
        biov8: 2,
      },
      {
        optic_labs: "Thymosin Alpha-1 10mg",
        rainbow_peptide: "thymosin alpha 1 capsules 10mg；thymosin alpha 1",
        bt7: "Thymosin Alpha-1 – 10mg",
        biolongevity: "Thymosin Alpha 1 BioStrips；Thymosin Alpha 1 (10mg)",
        limitless: "Thymosin Alpha 1 RGDR；Thymosin Alpha-1",
        amino_usa: "Thymosin Alpha-1 5mg",
        gl_vitality: "Thymosin Alpha-1",
        biov8: "Thymosin Alpha 1；Thymosin Alpha 1 ICCC",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "5mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "BioStrips", "胶囊"],
    },
    supplyMetrics: {
      stockWeeks: "2–4 周",
      stockMode: "finished_small_batch",
      leadTimeDays: 21,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["免疫相关肽类"],
    stockingLogic: "8/12 平台覆盖；免疫相关平台常见",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-aod9604",
    product: "AOD-9604",
    primarySpec: "5mg / 10mg",
    category: "metabolic",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 1,
        limitless: 1,
        amino_usa: 1,
        gl_vitality: 1,
        biov8: 2,
      },
      {
        elite_peps: "AOD-9604 10mg (Lipolytic Fragment 176-191)",
        aussie_peptides: "AOD-9604 (5mg)",
        optic_labs: "AOD-9604 5mg",
        rainbow_peptide: "aod 9604",
        limitless: "AOD 9604",
        amino_usa: "AOD-9604 10mg",
        gl_vitality: "AOD-9604",
        biov8: "AOD-9604；AOD-9604 ICCC",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["5mg", "10mg"],
      consensusSpec: "5mg、10mg",
      forms: ["冻干粉"],
    },
    supplyMetrics: {
      stockWeeks: "轻库存",
      stockMode: "finished_small_batch",
      leadTimeDays: 21,
    },
    auRegulatoryRisk: "high",
    regulatoryNotes: ["与体重管理监管风险相关"],
    stockingLogic: "8/12 平台覆盖；轻库存，注意监管变化",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-ss31",
    product: "SS-31",
    displayNameZh: "Elamipretide",
    primarySpec: "10mg",
    category: "metabolic",
    tier: "trial",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        elite_peps: 1,
        ozpeps: 2,
        aussie_peptides: 1,
        optic_labs: 1,
        rainbow_peptide: 2,
        bt7: 1,
      },
      {
        elite_peps: "SS-31 (Elamipretide) 10mg – Research Peptide",
        ozpeps: "SS-31 10mg；SS-31 50mg",
        aussie_peptides: "SS-31 (10mg)",
        optic_labs: "SS-31 10mg",
        rainbow_peptide: "ss 31 capsules 20mg；ss 31",
        bt7: "SS-31 – 10mg",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "50mg", "20mg capsules"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "胶囊"],
    },
    supplyMetrics: {
      stockWeeks: "轻库存",
      stockMode: "finished_small_batch",
      leadTimeDays: 28,
    },
    auRegulatoryRisk: "medium",
    regulatoryNotes: ["定位清晰但需求面较窄"],
    stockingLogic: "6/12 平台覆盖；轻库存",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-retatrutide",
    product: "Retatrutide",
    primarySpec: "10mg / 20mg",
    category: "metabolic",
    tier: "avoid",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        ozpeps: 2,
        aussie_peptides: 3,
        optic_labs: 1,
        rainbow_peptide: 2,
        premiumpeps: 1,
        bt7: 3,
      },
      {
        ozpeps: "Retatrutide 20mg；Retatrutide 30mg",
        aussie_peptides:
          "Retatrutide (10mg)；Retatrutide (20mg)；Retatrutide Starter Kit (Bundle)；Retatrutide Value Bundle；Retatrutide (30mg)；Retatrutide (60mg)；Retatrutide (15mg)",
        optic_labs: "Retatrutide 5mg / 10mg / 15mg / 20mg / 30mg",
        rainbow_peptide: "retatrutide capsules 10mg；retatrutide",
        premiumpeps: "Retatrutide (10mg)",
        bt7: "Retatru 10mg；Retatrutide – 10mg；Retatrutide – 20 mg",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "20mg", "30mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "胶囊", "Bundle"],
    },
    supplyMetrics: {
      stockWeeks: "订单制",
      stockMode: "order_only",
      leadTimeDays: 45,
      reorderNote: "客户预测 → 资质确认 → 定金 → 排产 → 检测 → 交付",
    },
    auRegulatoryRisk: "high",
    regulatoryNotes: [
      "减重肽类，法规/处方政策变化可能导致平台突然下架",
      "上架热度不等于稳定复购",
    ],
    stockingLogic: "6/12 平台有上架但仅接订单，不主动压货",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-tirzepatide",
    product: "Tirzepatide",
    primarySpec: "10mg / 20mg",
    category: "metabolic",
    tier: "avoid",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        ozpeps: 1,
        aussie_peptides: 3,
        optic_labs: 1,
        rainbow_peptide: 2,
        premiumpeps: 1,
        bt7: 1,
      },
      {
        ozpeps: "Tirzepatide 30mg",
        aussie_peptides: "Tirzepatide (20mg)；Tirzepatide (40mg)；Tirzepatide (60mg)",
        optic_labs: "Tirzepatide 10mg",
        rainbow_peptide: "tirzepatide 10mg；tirzepatide capsules 10mg",
        premiumpeps: "Tirzepatide (10mg)",
        bt7: "Tirzepatide – 10mg",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg", "20mg", "40mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉", "胶囊"],
    },
    supplyMetrics: {
      stockWeeks: "订单制",
      stockMode: "order_only",
      leadTimeDays: 45,
    },
    auRegulatoryRisk: "high",
    regulatoryNotes: ["受管制 GLP 类肽；订单制"],
    stockingLogic: "6/12 平台覆盖；不主动压货",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-semaglutide",
    product: "Semaglutide",
    primarySpec: "10mg",
    category: "metabolic",
    tier: "avoid",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      { ozpeps: 1, bt7: 1 },
      { ozpeps: "Semaglutide 10mg", bt7: "Semaglutide – 10mg" },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉"],
    },
    supplyMetrics: {
      stockWeeks: "订单制",
      stockMode: "order_only",
      leadTimeDays: 45,
    },
    auRegulatoryRisk: "high",
    regulatoryNotes: ["TGA 严格管制；仅 2/12 平台上架"],
    stockingLogic: "覆盖低 + 监管极高 → 订单制",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-cagrilintide",
    product: "Cagrilintide",
    primarySpec: "5mg / 10mg",
    category: "metabolic",
    tier: "avoid",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      {
        aussie_peptides: 1,
        rainbow_peptide: 1,
        biolongevity: 1,
        amino_usa: 2,
      },
      {
        aussie_peptides: "Cagrilintide (5mg)",
        rainbow_peptide: "cagrilintide 5mg",
        biolongevity: "Cagrilintide (Amylin Analog) (5mg)",
        amino_usa: "Cagrilintide 5mg；Cagrilintide 10mg",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["5mg", "10mg"],
      consensusSpec: "5mg",
      forms: ["冻干粉"],
    },
    supplyMetrics: {
      stockWeeks: "订单制",
      stockMode: "order_only",
      leadTimeDays: 45,
    },
    auRegulatoryRisk: "high",
    regulatoryNotes: ["Amylin 类似物，监管敏感"],
    stockingLogic: "4/12 平台覆盖；订单制",
    lastReviewed: "2026-06-22",
  },
  {
    id: "pm-melanotan",
    product: "Melanotan I / II",
    primarySpec: "10mg",
    category: "other",
    tier: "avoid",
    tierSource: "manual",
    platformTotal: 12,
    ...p(
      { optic_labs: 1, aussie_peptides: 1, bt7: 1 },
      {
        optic_labs: "Melanotan 2 10mg",
        aussie_peptides: "Melanotan I (10mg)",
        bt7: "Melanotan I – 10mg",
      },
    ),
    commonBlends: [],
    specProfile: {
      primarySpecs: ["10mg"],
      consensusSpec: "10mg",
      forms: ["冻干粉"],
    },
    supplyMetrics: {
      stockWeeks: "订单制",
      stockMode: "order_only",
      leadTimeDays: 45,
    },
    auRegulatoryRisk: "high",
    regulatoryNotes: ["TGA 执法关注产品；覆盖极低"],
    stockingLogic: "1–2/12 平台覆盖；不建议压货",
    lastReviewed: "2026-06-22",
  },
];

export const productBlends: ProductBlend[] = [
  {
    id: "blend-bpc-tb",
    name: "BPC-157 + TB-500",
    components: [
      { product: "BPC-157", amount: "10mg" },
      { product: "TB-500", amount: "10mg" },
    ],
    platformCoverage: 10,
    platformTotal: 12,
    tier: "trial",
    stockMode: "finished_small_batch",
  },
  {
    id: "blend-glow",
    name: "GLOW",
    components: [
      { product: "GHK-Cu", amount: "50mg" },
      { product: "BPC-157", amount: "10mg" },
      { product: "TB-500", amount: "10mg" },
    ],
    platformCoverage: 8,
    platformTotal: 12,
    tier: "trial",
    stockMode: "delayed_fill",
  },
  {
    id: "blend-klow",
    name: "KLOW",
    components: [
      { product: "GHK-Cu", amount: "50mg" },
      { product: "BPC-157", amount: "10mg" },
      { product: "TB-500", amount: "10mg" },
      { product: "KPV", amount: "10mg" },
    ],
    platformCoverage: 7,
    platformTotal: 12,
    tier: "trial",
    stockMode: "delayed_fill",
  },
];

export const productMonitorRecords: ProductMonitorRecord[] = rawRecords.map(
  (r) => enrichRecordScores(r),
);

export function getRecordById(id: string) {
  return productMonitorRecords.find((r) => r.id === id);
}

export function getBlendsForProduct(productId: string) {
  const record = getRecordById(productId);
  if (!record) return [];
  return productBlends.filter((b) => record.commonBlends.includes(b.id));
}
