import type { PathEdge, PathNode } from "./types";

/** Supply chain path nodes — B2B2C-处方医生 / B2B2C-RUO平台 / B2C-跨境零售 */
export const pathGraphNodes: PathNode[] = [
  // B2B2C-处方医生
  {
    id: "n1",
    pathId: "path-b2b-compounding",
    sequence: 1,
    nodeType: "manufacturer",
    displayName: "Wuhan PeptideTech Co.",
    region: "CN",
    riskLevel: "low",
    status: "active",
    documentCompletion: 100,
  },
  {
    id: "n2",
    pathId: "path-b2b-compounding",
    sequence: 2,
    nodeType: "exporter",
    displayName: "Shanghai BioExport Trading",
    region: "CN",
    riskLevel: "low",
    status: "active",
    documentCompletion: 85,
  },
  {
    id: "n3",
    pathId: "path-b2b-compounding",
    sequence: 3,
    nodeType: "import_permit_holder",
    displayName: "AusPharm Import Holdings",
    region: "AU",
    riskLevel: "medium",
    status: "active",
    documentCompletion: 80,
  },
  {
    id: "n4",
    pathId: "path-b2b-compounding",
    sequence: 4,
    nodeType: "quality_testing_lab",
    displayName: "National Analytical Labs",
    region: "AU",
    riskLevel: "low",
    status: "active",
    documentCompletion: 100,
  },
  {
    id: "n5",
    pathId: "path-b2b-compounding",
    sequence: 5,
    nodeType: "compounding_pharmacy",
    displayName: "Precision Compounding VIC",
    region: "AU",
    riskLevel: "medium",
    status: "active",
    documentCompletion: 67,
  },
  {
    id: "n6",
    pathId: "path-b2b-compounding",
    sequence: 6,
    nodeType: "telehealth_platform",
    displayName: "Telehealth Prescriber Platform",
    region: "AU",
    riskLevel: "medium",
    status: "active",
    documentCompletion: 90,
  },
  {
    id: "n7",
    pathId: "path-b2b-compounding",
    sequence: 7,
    nodeType: "end_customer_b2c",
    displayName: "C-End Patient",
    region: "AU",
    riskLevel: "low",
    status: "active",
    documentCompletion: 100,
  },
  // B2B2C-RUO平台
  {
    id: "n11",
    pathId: "path-clinic-prescriber",
    sequence: 1,
    nodeType: "manufacturer",
    displayName: "Wuhan PeptideTech Co.",
    region: "CN",
    riskLevel: "low",
    status: "active",
    documentCompletion: 100,
  },
  {
    id: "n12",
    pathId: "path-clinic-prescriber",
    sequence: 2,
    nodeType: "exporter",
    displayName: "Shanghai BioExport Trading",
    region: "CN",
    riskLevel: "low",
    status: "active",
    documentCompletion: 85,
  },
  {
    id: "n13",
    pathId: "path-clinic-prescriber",
    sequence: 3,
    nodeType: "import_permit_holder",
    displayName: "AusPharm Import Holdings",
    region: "AU",
    riskLevel: "medium",
    status: "active",
    documentCompletion: 80,
  },
  {
    id: "n14",
    pathId: "path-clinic-prescriber",
    sequence: 4,
    nodeType: "quality_testing_lab",
    displayName: "National Analytical Labs",
    region: "AU",
    riskLevel: "low",
    status: "active",
    documentCompletion: 100,
  },
  {
    id: "n15",
    pathId: "path-clinic-prescriber",
    sequence: 5,
    nodeType: "compounding_pharmacy",
    displayName: "Precision Compounding VIC",
    region: "AU",
    riskLevel: "medium",
    status: "active",
    documentCompletion: 67,
  },
  {
    id: "n16",
    pathId: "path-clinic-prescriber",
    sequence: 6,
    nodeType: "ruo_platform",
    displayName: "RUO Supply Platform",
    region: "AU",
    riskLevel: "medium",
    status: "active",
    documentCompletion: 75,
  },
  {
    id: "n17",
    pathId: "path-clinic-prescriber",
    sequence: 7,
    nodeType: "research_end_user",
    displayName: "Research Platform / Personnel",
    region: "AU",
    riskLevel: "medium",
    status: "active",
    documentCompletion: 85,
  },
  // B2C-跨境零售
  {
    id: "n18",
    pathId: "path-grey-retail",
    sequence: 1,
    nodeType: "manufacturer",
    displayName: "Wuhan PeptideTech Co.",
    region: "CN",
    riskLevel: "low",
    status: "active",
    documentCompletion: 100,
  },
  {
    id: "n19",
    pathId: "path-grey-retail",
    sequence: 2,
    nodeType: "exporter",
    displayName: "Shanghai BioExport Trading",
    region: "CN",
    riskLevel: "medium",
    status: "active",
    documentCompletion: 70,
  },
  {
    id: "n20",
    pathId: "path-grey-retail",
    sequence: 3,
    nodeType: "quality_testing_lab",
    displayName: "Third-Party Lab (optional)",
    region: "AU",
    riskLevel: "medium",
    status: "active",
    optional: true,
    documentCompletion: 60,
  },
  {
    id: "n21",
    pathId: "path-grey-retail",
    sequence: 4,
    nodeType: "end_customer_b2c",
    displayName: "C-End Individual",
    region: "AU",
    riskLevel: "high",
    status: "active",
    documentCompletion: 20,
  },
];

export const pathGraphEdges: PathEdge[] = [
  { id: "e1", pathId: "path-b2b-compounding", fromNodeId: "n1", toNodeId: "n2", transportMode: "domestic", estimatedDays: 2, requiredDocuments: ["coa", "gmp_cert"], riskLevel: "low", status: "active" },
  { id: "e2", pathId: "path-b2b-compounding", fromNodeId: "n2", toNodeId: "n3", transportMode: "air", estimatedDays: 5, requiredDocuments: ["import_permit", "tga_approval"], riskLevel: "medium", status: "active" },
  { id: "e3", pathId: "path-b2b-compounding", fromNodeId: "n3", toNodeId: "n4", transportMode: "domestic", estimatedDays: 2, requiredDocuments: ["coa"], riskLevel: "low", status: "active" },
  { id: "e4", pathId: "path-b2b-compounding", fromNodeId: "n4", toNodeId: "n5", transportMode: "domestic", estimatedDays: 1, requiredDocuments: ["pharmacy_license", "compounding_registration"], riskLevel: "medium", status: "active" },
  { id: "e5", pathId: "path-b2b-compounding", fromNodeId: "n5", toNodeId: "n6", transportMode: "domestic", estimatedDays: 1, requiredDocuments: ["state_specific"], riskLevel: "medium", status: "active" },
  { id: "e6", pathId: "path-b2b-compounding", fromNodeId: "n6", toNodeId: "n7", transportMode: "courier", estimatedDays: 2, requiredDocuments: [], riskLevel: "low", status: "active" },
  { id: "e10", pathId: "path-clinic-prescriber", fromNodeId: "n11", toNodeId: "n12", transportMode: "domestic", estimatedDays: 2, requiredDocuments: ["coa", "gmp_cert"], riskLevel: "low", status: "active" },
  { id: "e11", pathId: "path-clinic-prescriber", fromNodeId: "n12", toNodeId: "n13", transportMode: "air", estimatedDays: 5, requiredDocuments: ["import_permit"], riskLevel: "medium", status: "active" },
  { id: "e12", pathId: "path-clinic-prescriber", fromNodeId: "n13", toNodeId: "n14", transportMode: "domestic", estimatedDays: 2, requiredDocuments: ["coa"], riskLevel: "low", status: "active" },
  { id: "e13", pathId: "path-clinic-prescriber", fromNodeId: "n14", toNodeId: "n15", transportMode: "domestic", estimatedDays: 1, requiredDocuments: ["pharmacy_license"], riskLevel: "medium", status: "active" },
  { id: "e14", pathId: "path-clinic-prescriber", fromNodeId: "n15", toNodeId: "n16", transportMode: "domestic", estimatedDays: 1, requiredDocuments: ["compounding_registration"], riskLevel: "medium", status: "active" },
  { id: "e15", pathId: "path-clinic-prescriber", fromNodeId: "n16", toNodeId: "n17", transportMode: "courier", estimatedDays: 2, requiredDocuments: [], riskLevel: "medium", status: "active" },
  { id: "e16", pathId: "path-grey-retail", fromNodeId: "n18", toNodeId: "n19", transportMode: "courier", estimatedDays: 7, requiredDocuments: ["coa"], riskLevel: "high", status: "active" },
  { id: "e17", pathId: "path-grey-retail", fromNodeId: "n19", toNodeId: "n20", transportMode: "courier", estimatedDays: 3, requiredDocuments: ["coa"], riskLevel: "medium", status: "alternative" },
  { id: "e18", pathId: "path-grey-retail", fromNodeId: "n20", toNodeId: "n21", transportMode: "courier", estimatedDays: 2, requiredDocuments: [], riskLevel: "high", status: "active" },
  { id: "e19", pathId: "path-grey-retail", fromNodeId: "n19", toNodeId: "n21", transportMode: "courier", estimatedDays: 5, requiredDocuments: [], riskLevel: "high", status: "alternative" },
];
